this["adcirc"] = this["adcirc"] || {};
this["adcirc"]["templates"] = this["adcirc"]["templates"] || {};

this["adcirc"]["templates"]["line_plot"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : {}, alias2=helpers.helperMissing, alias3="function", alias4=container.escapeExpression;

  return "<div id=\""
    + alias4(((helper = (helper = helpers.id || (depth0 != null ? depth0.id : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"id","hash":{},"data":data}) : helper)))
    + "\" class=\"plot row\">\n    <div class=\"col-sm-4 col-md-3 col-lg-2 options\">\n\n        <div class=\"title\">\n            New Plot<i class=\"fa fa-bars pull-right clickable-icon\"></i>\n        </div>\n\n        <!-- Basic plot options -->\n\n        <div class=\"plot-form form-horizontal\">\n\n            <label class=\"col-sm-12 form-title\">\n                Options\n                <i class=\"fa fa-chevron-down pull-right clickable-icon\"></i>\n                <i class=\"fa fa-plus pull-right clickable-icon\"></i>\n            </label>\n\n            <!-- Width -->\n            <div class=\"form-group form-group-sm form-item\">\n                <label class=\"col-sm-5 control-label\">\n                    Width:\n                </label>\n                <div class=\"col-sm-7 control-content\">\n                    <div class=\"input-group\">\n                        <input class=\"form-control\" type=\"number\" min=\"0\" max=\"100\" value=\"100\">\n                        <div class=\"input-group-addon\">%</div>\n                    </div>\n                </div>\n            </div>\n\n            <!-- Height -->\n            <div class=\"form-group form-group-sm form-item form-item-last\">\n                <label class=\"col-sm-5 control-label\">\n                    Height:\n                </label>\n                <div class=\"col-sm-7 control-content\">\n                    <div class=\"input-group\">\n                        <input class=\"form-control\" type=\"number\" min=\"0\" value=\"400\">\n                        <div class=\"input-group-addon\">px</div>\n                    </div>\n                </div>\n            </div>\n\n        </div>\n\n        <!-- Dataset options -->\n\n        <div class=\"plot-form form-horizontal\">\n\n            <label class=\"col-sm-12 form-title\">\n                Datasets\n                <i class=\"fa fa-chevron-down pull-right clickable-icon\"></i>\n                <i class=\"fa fa-plus pull-right clickable-icon\"></i>\n            </label>\n\n            <!-- fort.63 -->\n            <div class=\"form-group form-group-sm form-item form-item-last\">\n                <label class=\"col-sm-5 control-label\">\n                    Node:\n                </label>\n                <div class=\"col-sm-7 control-content\">\n                    <input id=\""
    + alias4(((helper = (helper = helpers.node_picker || (depth0 != null ? depth0.node_picker : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"node_picker","hash":{},"data":data}) : helper)))
    + "\" class=\"form-control\" type=\"number\" min=\"1\" max=\"1000\" value=\"1\">\n                </div>\n            </div>\n\n        </div>\n        \n    </div>\n    <div class=\"col-sm-8 col-md-9 col-lg-10 chart\">\n\n    </div>\n</div>";
},"useData":true});